# Generated by Django 4.0.6 on 2022-07-31 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='object_id',
        ),
    ]
