# Generated by Django 4.0.6 on 2022-07-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_remove_transactions_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowerlot',
            old_name='prise',
            new_name='price',
        ),
    ]
