# Generated by Django 4.0.6 on 2022-07-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_rename_prise_flowerlot_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowerlot',
            old_name='amount',
            new_name='quantity',
        ),
    ]
