# Generated by Django 4.1 on 2022-08-06 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0006_alter_flowerlot_options_alter_flowerlot_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='Заголовок')),
                ('body', models.CharField(max_length=250, verbose_name='Отзыв')),
            ],
        ),
        migrations.CreateModel(
            name='Salesman_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='Заголовок')),
                ('body', models.CharField(max_length=250, verbose_name='Отзыв')),
            ],
        ),
        migrations.AlterField(
            model_name='flowerlot',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'отображать'), ('F', 'не отображать')], default='O', help_text='Отображение лота', max_length=1),
        ),
        migrations.AlterField(
            model_name='flowerlot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('S', 'Seller'), ('B', 'Buyer')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='salesman_feedback',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_salesman_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesman_feedback',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesman_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lot_feedback',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_lot_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lot_feedback',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lot_comments', to='flowers.flowerlot'),
        ),
    ]
